#!/usr/bin/env python3

import string
import random


word_file = "words.txt"
word_list = []
# fill up the word_list
with open(word_file, 'r') as words:
    for line in words:
        # remove white space and make everything lowercase
        word = line.strip().lower()

            word_list.append(word)
def generate(word = 4, length=4, digits_count=0, upper_count=0, special_count=0):
  
    lower_count = max(0, length - digits_count - upper_count - special_count)

    digits = random.sample(string.digits, digits_count)
    specials = random.sample(string.punctuation, special_count)
    upper = random.sample(string.ascii_uppercase, upper_count)
    lower = random.sample(string.ascii_lowercase, lower_count)

    password = list(random.choice(word_list) + upper + digits + lower + specials)
    random.shuffle(password)
    return "".join(password)


def main():
    import argparse

    parser = argparse.ArgumentParser(description='Password generator')
    arser.add_argument("-w", '--word', type=int, default=4,
                        help='Password length.')
    
    parser.add_argument("-l", '--length', type=int, default=4,
                        help='Password length.')
    parser.add_argument("-n", '--digits_count', type=int, default=0,
                        help='Digits count.')
    parser.add_argument("-c", '--upper_count', type=int, default=0,
                        help='Uppper characters count.')
    parser.add_argument("-s", '--special_count', default=0,
                        type=int, help='Special characters count.')

    args = parser.parse_args()
    password = generate(random.choice(word_list),
        length=args.length,
        upper_count=args.upper_count,
        digits_count=args.digits_count,
        special_count=args.special_count
    )

    print(password)


if __name__ == "__main__":
    main()
